services:
  ros2-sim:
    image: janyljumadinova/ros2-environment:latest
    container_name: ros2-turtlebot3
    ports:
      - "6080:80"
    shm_size: "1gb"
    volumes:
      - ./maps:/home/ubuntu/project_maps
      - ./src:/home/ubuntu/project_src
    environment:
      - RESOLUTION=1280x720
      - TURTLEBOT3_MODEL=burger
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
